import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "Read the terms governing use of BizToolLab business calculators, information, and website services.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 text-slate-900">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-5">
          <a href="/" className="text-2xl font-bold">
            BizToolLab
          </a>

          <a
            href="/"
            className="text-sm font-medium text-slate-600 hover:text-slate-950"
          >
            Back to Home
          </a>
        </div>
      </header>

      <section className="mx-auto max-w-4xl px-6 py-16">
        <p className="text-sm font-semibold uppercase tracking-wider text-slate-500">
          Legal
        </p>

        <h1 className="mt-3 text-4xl font-bold tracking-tight">
          Terms of Use
        </h1>

        <p className="mt-4 text-sm text-slate-500">
          Last updated: September 8, 2026
        </p>

        <div className="mt-10 space-y-10 leading-7 text-slate-600">
          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              General use
            </h2>

            <p className="mt-3">
              By using BizToolLab, you agree to use the website and its tools
              for lawful purposes and in accordance with these Terms of Use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              Educational and informational purposes
            </h2>

            <p className="mt-3">
              BizToolLab calculators, estimates, examples, and information are
              provided for general planning, educational, and informational
              purposes only.
            </p>

            <p className="mt-3">
              Results should not be considered financial, accounting, tax,
              legal, investment, lending, or other professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              Accuracy of calculations
            </h2>

            <p className="mt-3">
              We aim to provide useful and understandable calculations, but
              actual business results may differ substantially from estimates
              generated by BizToolLab.
            </p>

            <p className="mt-3">
              Users are responsible for reviewing their own assumptions and
              verifying information before making business or financial
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              No guarantee of results
            </h2>

            <p className="mt-3">
              BizToolLab does not guarantee profitability, investment returns,
              business performance, cost savings, financing approval, or any
              other particular outcome.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              Third-party links and services
            </h2>

            <p className="mt-3">
              BizToolLab may contain links to third-party websites, products,
              advertisements, or services. We are not responsible for the
              content, availability, policies, or practices of third-party
              services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900">
              Changes to these terms
            </h2>

            <p className="mt-3">
              These Terms of Use may be updated periodically as BizToolLab
              evolves. Continued use of the website after changes are published
              constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>
      </section>
    </main>
  );
}